#!/bin/bash -e

if [ $# -gt 1 ] || ( [ $# -eq 1 ] && [ $1 != "d" ] && [ $1 != "c" ] && [ $1 != "b" ] )
then
	echo
	echo "Usage: $0 [<option>]"
	echo
	echo "<option> could be any one of:"
	echo "d: Download"
	echo "c: Download & Configure"
	echo "b: Download, Configure & Build"
	echo "<none>: Download, Configure, Build & consolidate Images"
	echo
	exit 1
fi
option=$1

cd `dirname ${BASH_SOURCE}`

. ../check_setup

LINUX_CONFIG_DIR=`pwd`/Configs

if [ ! -d linux-${LINUX_VERSION} ]
then
	# Download the linux source
	wget -c -P ${DOWNLOADS} ${LINUX_URL}/linux-${LINUX_VERSION}.tar.xz
	tar -xf ${DOWNLOADS}/linux-${LINUX_VERSION}.tar.xz
fi

cd linux-${LINUX_VERSION}

[ "${option}" = "d" ] && exit 0

# Configure the linux source
cp ${LINUX_CONFIG_DIR}/config.${LINUX_VERSION}.default .config
ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILE} make oldconfig

[ "${option}" = "c" ] && exit 0

# Build the linux source
ARCH=${ARCH} CROSS_COMPILE=${CROSS_COMPILE} make

[ "${option}" = "b" ] && exit 0

# Copy the dtb & linux images
cp arch/arm/boot/dts/am335x-boneblack.dtb arch/arm/boot/zImage ${IMAGES}
