#!/bin/bash

if [ $# -eq 2 ] && [ "$1" = "-d" ]
then
	DUMP=1
	USDDEV="$2"
elif [ $# -eq 1 ]
then
	DUMP=0
	USDDEV="$1"
else
	echo "Usage: $0 [ -d ] <usd_device_file>"
	exit 1
fi

USDDEVTYPE=`lsblk -pl | grep "${USDDEV} " | awk '{print $6}'`
if [ "${USDDEVTYPE}" != "disk" ]
then
	echo "Invalid uSD block device file ${USDDEV}"
	exit 2
fi

USDPARTDEV=`lsblk -pl | grep "${USDDEV}" | tail -n +2 | head -1 | awk '{print $1}'`
USDPARTDEVTYPE=`lsblk -pl | grep "${USDDEV}" | tail -n +2 | head -1 | awk '{print $6}'`
if [ "${USDPARTDEVTYPE}" != "part" ]
then
	echo "uSD not having the first partition. Create it."
	exit 3
fi

if [ `id -u` != 0 ]
then
	echo "You need root privileges to run this script"
	exit 4
fi

echo -n "You are going to lose your data in the uSD (${USDDEV}). Continue? [y|N]: "
read resp
if [ "${resp}" != "y" ]
then
	echo "Aborting ... done."
	exit 5
fi

if (grep ${USDPARTDEV} /proc/self/mounts > /dev/null)
then
	if (! umount ${USDPARTDEV} 2> /dev/null)
	then
		echo "Unable to unmount uSD device file ${USDPARTDEV}"
		exit 6
	fi
fi

if (! mkfs.vfat -n BBBREC ${USDPARTDEV} 2> /dev/null >&2)
then
	echo "Unable to create FAT32 file system on the uSD"
	exit 7
fi

MNT=/mnt
if (! mount ${USDPARTDEV} ${MNT} 2> /dev/null)
then
	echo "Invalid uSD device file ${USDPARTDEV} or already mounted"
	exit 8
fi

cd `dirname $0`

if [ ! -d ../Images ]
then
	echo "`basename $0` is placed out of tree"
	umount ${MNT}
	exit 9
fi

IMAGES="MLO u-boot.img uEnv.txt rd-ext2.bin zImage am335x-boneblack.dtb"

cd ../Images
if (! cp ${IMAGES} ${MNT} 2> /dev/null)
then
	echo "Missing images to prepare the uSD"
	cd ${MNT}
	rm -f ${IMAGES}
	cd - > /dev/null
	umount ${MNT}
	exit 10
fi
cd - > /dev/null

if [ ${DUMP} -eq 0 ]
then
	umount ${MNT}
	parted ${USDDEV} set 1 boot on 2> /dev/null # Make the first partition bootable
	dd if=/dev/zero of=${USDDEV} bs=512 seek=1 count=2047 conv=notrunc 2> /dev/null
	echo "uSD prepared successfully"
else
	rm ${MNT}/MLO # Remove it to stop interfering
	umount ${MNT}
	cd ../Images
	dd if=MLO of=${USDDEV} bs=512 seek=256 count=256 conv=notrunc 2> /dev/null
	dd if=u-boot.img of=${USDDEV} bs=512 seek=768 count=1024 conv=notrunc 2> /dev/null
	cd - > /dev/null
	echo "uSD w/ raw dump prepared successfully"
fi
